[project]
name = "test-package-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Chaya Carey", email = "chaya.carey@dbtlabs.com" }
]
requires-python = ">=3.9"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"


[project.scripts]
test-package-1 = "test_package_1.main:app"